### ISSUE TITLE
Issue with OBD Inject

### ISSUE THREAD

**Issue by x6DEMON6x** [KreAch3R/tpms-oap#2]
Hi can you help me with my project with obd inject my parameters are not showing up in the dashboard of oap?

**Comment by KreAch3R** [comment]
Are you trying to adapt my code of tpms-oap for your Bluetooth tpms? Do you have the same ones?

**Comment by x6DEMON6x** [comment]
no i´m trying to adapt your code for i2c sensors

**Comment by x6DEMON6x** [comment]
i can send you my code if you want. do you have discord?

**Comment by KreAch3R** [comment]
Then post a new thread over at BlueWave studios or upload it here on GitHub and mention me, and I'll be happy to help if I can. This one isn't the right place to talk about another project.
